api = "0.6"

[buildpack]
  id = "io.adaptable/buildpack-launch"
  version = "0.0.4"
  description = "Provides launch configuration"

[[stacks]]
  id = "*"

[metadata]
  include-files = ["build/build", "bin/detect", "bin/jsontoml"]

